### ISSUE TITLE
我吧出错发到你那个子目录下了，这个是连接

### ISSUE THREAD

**Issue by awmbtc** [alexzhangs/aws-cfn-vpn#2]
https://github.com/alexzhangs/aws-cfn-vpc-peer-accepter/issues/1#issue-1089202799

**Comment by alexzhangs** [comment]
> Note: If you are proceeding without the tools, then you will have to manually edit config files and upload templates and Lambda functions to S3, and handle the parameters for each nested template.

If you go without the deploy tool mentioned in the doc, then you will have to upload all nested templates and the non-inline lambda functions to S3, then get the S3 URLs of them and set the parameters for the root template accordingly:

```
*StackTemplateURL
S3BucketForLambda*
S3KeyForLambda*
```

Again, there will be a lot of works if you go without the deploy tool, I never do that, and I can't image the work efforts doing all this by hands especially with a cluster. And that's also the reason there's no detail steps explained for this.

If you really really do want to do this way, see the [Troubleshooting](https://github.com/alexzhangs/aws-cfn-vpn#troubleshooting) section for any deploy error.

**Comment by awmbtc** [comment]
> > 注意：如果您在没有工具的情况下继续操作，那么您将必须手动编辑配置文件并将模板和 Lambda 函数上传到 S3，并处理每个嵌套模板的参数。
> 
> 如果您没有使用文档中提到的部署工具，那么您必须将所有嵌套模板和非内联 lambda 函数上传到 S3，然后获取它们的 S3 URL 并相应地设置根模板的参数：
> 
> ```
> *StackTemplateURL
> S3BucketForLambda*
> S3KeyForLambda*
> ```
> 
> 同样，如果没有部署工具，将会有很多工作，我从不这样做，而且我无法想象手工完成所有这些工作的工作，尤其是使用集群。这也是没有为此解释详细步骤的原因。
> 
> 如果您真的真的想这样做，请参阅[故障排除](https://github.com/alexzhangs/aws-cfn-vpn#troubleshooting)部分以了解任何部署错误。

好吧，我放弃了。已经尝试了好多次。

**Comment by alexzhangs** [comment]
close this issue
