### ISSUE TITLE
 xsh load xsh-lib/aws.  &. xsh/repo/xsh-lib/aws' 

### ISSUE THREAD

**Issue by awmbtc** [alexzhangs/aws-cfn-vpn#3]
![image](https://user-images.githubusercontent.com/96400309/147723887-69444d14-8ee7-4e9f-8377-d82bd040e48f.png)
`[cloudshell-user@ip-10-0-160-20 ~]$ xsh load xsh-lib/core
Cloning into '/home/cloudshell-user/.xsh/repo/xsh-lib/core'...
remote: Enumerating objects: 2240, done.
remote: Counting objects: 100% (191/191), done.
remote: Compressing objects: 100% (135/135), done.
remote: Total 2240 (delta 81), reused 132 (delta 46), pack-reused 2049
Receiving objects: 100% (2240/2240), 298.44 KiB | 18.65 MiB/s, done.
Resolving deltas: 100% (1142/1142), done.
__xsh_git_force_update: INFO: Updating repo to 0.3.3.
HEAD is now at 5d64f2d Create __init__.sh
[cloudshell-user@ip-10-0-160-20 ~]$ xsh load xsh-lib/aws
Cloning into '/home/cloudshell-user/.xsh/repo/xsh-lib/aws'...
remote: Enumerating objects: 993, done.
remote: Counting objects: 100% (335/335), done.
remote: Compressing objects: 100% (182/182), done.
remote: Total 993 (delta 194), reused 253 (delta 131), pack-reused 658
Receiving objects: 100% (993/993), 163.59 KiB | 11.68 MiB/s, done.
Resolving deltas: 100% (454/454), done.
__xsh_git_force_update: INFO: Updating repo to latest.
HEAD is now at 7cfe29a fix defect: .xsh/lib/aws/functions/cfn/__init__.sh: line 91: !XSH_AWS_CFN__STACK_STATUS[@]: parameter null or not set`

**Comment by alexzhangs** [comment]
> HEAD is now at 7cfe29a fix defect: .xsh/lib/aws/functions/cfn/__init__.sh: line 91: !XSH_AWS_CFN__STACK_STATUS[@]: parameter null or not set

This line is a normal info message, the "error" is a part of the commit message.
There's nothing wrong here.
