### ISSUE TITLE
aws-cfn-vpn/config.sh: line 127: 0\n1\n2: syntax error: invalid arithmetic operator (error token is "\n1\n2")

### ISSUE THREAD

**Issue by awmbtc** [alexzhangs/aws-cfn-vpn#4]
![image](https://user-images.githubusercontent.com/96400309/147727686-eca3ee52-ada2-4937-b9be-29da0d43ef3a.png)

**Comment by alexzhangs** [comment]
this is a bug of config.sh with GNU seq command.
I'll fix it.

**Comment by alexzhangs** [comment]
fixed in commit [8961fce](https://github.com/alexzhangs/aws-cfn-vpn/commit/8961fce9f1b0ee8a55797d8766dd0f0638b2f096)
