### ISSUE TITLE
File or directory fail to find

### ISSUE THREAD

**Issue by sayazaaa** [alexzhangs/aws-cfn-vpn#6]
# When create the manager stack and the node stacks, there's an bug exists.

###
 bash-3.2$ bash aws-cfn-vpn/deploy.sh-X 0-2-p profile-{0..23-c aws-cfn-vpn/vpn-{0..2}-sample.conf -r us-west-2
  activating profile: profile-0
  updating config file: aws-cfn-vpn/vpn-@-sample.conf
  updating OPTIONS: KeyPairName
  creating stack with config: aws-cfn-vpn/vpn-@-sample.comf
  aws-cfn-deplov: INFO: applvina config file options: aws-cfn-von/von-@-sample.conf
  aws-cfn-vpn/deplov.sh: line 153: aws-cfn-vpn/vpn-@-sample.conf: No such file or directory

**Comment by alexzhangs** [comment]
This issue is fixed.

The deployment scripts have been moved to: [xsh-lib/aws](https://github.com/xsh-lib/aws). The new deployer, `aws/cfn/vpn/deploy` or `aws/cfn/vpn/cluster` are recommended.
